# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c7378275affd2a51102e8c68158a5dae2258892ab1b7854be5326a9bec7d9626397132bdd1c69b15e091838b2e7ce8f3971d30aee68f9541c9e17b8829c772b

test:
  secret_key_base: 96170589d8c0a642c10362dfc5d5a2f71bb273a4cdf179c5752cc1f71315fbe032b85fffa0202de94a65a9f818b6c4e9ba9a2bed7bb9ab0c2b7a61419518d098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
